# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FHpZ64ayG4ddULw9X_d_6vnDYmk6fK9H
"""

nome = 'João'
nota = 10
print('O nome é: ', nome, 'e sua nota foi:', nota)
print('O nome é: %s e sua nota foi: %s' %(nome, nota))
print('O nome é: %s e sua nota foi: %.2f' %(nome, nota))

nome = input('Digite o seu nome: ')
nota = input('Digite a sua nota: ')
print('O nome é: ', nome, 'e sua nota foi:', nota)